### ISSUE TITLE
error on running

### ISSUE THREAD

**Issue by Zjemm** [tensult/Scout2-PDF-Reporter#1]
Hi i get the following:

[esadd@ansible Scout2-PDF-Reporter]$ node index.js -r ../scout2-report/inc-awsconfig/aws_config.js 
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:836:14)
Emitted 'error' event at:
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at Socket._destroy (net.js:606:3)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:838:10)

any idea what it is?

**Comment by koladilip** [comment]
Sorry for the delayed response, it is working for me, can you give me more details?
